media:
  input: content/images
  output: /content/images
  extensions: [jpg, jpeg, png, webp, gif]

content:
  - name: articles
    label: Articles
    type: collection
    path: content/articles
    format: yaml-frontmatter
    filename: '{{slug}}'
    extension: md
    fields:
      - name: title
        label: Title
        type: string
        required: true
      - name: slug
        label: Slug
        type: string
        required: true
      - name: date
        label: Date
        type: date
      - name: author
        label: Author
        type: string
      - name: image
        label: Cover Image
        type: image
      - name: excerpt
        label: Short Description
        type: text
      - name: body
        label: Article Content
        type: markdown

  - name: team
    label: Team Members
    type: collection
    path: content/team
    format: yaml-frontmatter
    filename: '{{name}}'
    extension: md
    fields:
      - name: name
        label: Name
        type: string
        required: true
      - name: role
        label: Role
        type: string
        required: true
      - name: photo
        label: Photo
        type: image
      - name: email
        label: Email
        type: string
      - name: social
        label: Social Links
        type: object
        fields:
          - name: linkedin
            label: LinkedIn
            type: string
          - name: github
            label: GitHub
            type: string
      - name: body
        label: Bio / Description
        type: markdown